/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import javax.swing.BorderFactory;
import java.awt.geom.RoundRectangle2D;
import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.UIManager;
import javax.swing.border.Border;

/**
 *
 * @author PC
 */
public class Menu extends javax.swing.JFrame {

    public Menu() {
        initComponents();
//        UIManager.put( "Button.arc", 999 );
        btnHome.putClientProperty("JButton.buttonType", "roundRect");

    }

    class FormaPrincipal extends JPanel {  //Para poner un degradado al panel

        protected void paintComponent(Graphics g) {
            Graphics2D g2d = (Graphics2D) g;

            int width = getWidth();
            int height = getHeight();

            // Definir proporciones: 20% para el primer color, 80% para el segundo color y un degradado suave más ancho
            int firstColorWidth = (int) (width * 0.22);  // 20% del ancho para el primer color
            int secondColorWidth = (int) (width * 0.80);  // 80% del ancho para el segundo color
            int gradientWidth = (int) (width * 0.05);  // Degradado del 20% del ancho para hacer la transición más suave

            // Crear los colores personalizados con valores RGB
            Color firstColor = new Color(175, 105, 232);  // Color de la izquierda
            Color secondColor = new Color(125, 165, 232);  // Color de la derecha

            // Parte sólida del primer color (20% del ancho)
            GradientPaint firstGradient = new GradientPaint(
                    0, 0, firstColor, // Comienza con el primer color (RGB)
                    firstColorWidth, 0, firstColor, // Primer color sólido hasta el 20%
                    true
            );
            g2d.setPaint(firstGradient);
            g2d.fillRect(0, 0, firstColorWidth, height);

            // Degradado entre el primer y segundo color (20% del ancho)
            GradientPaint gradient = new GradientPaint(
                    firstColorWidth, 0, firstColor, // Comienza con el primer color
                    firstColorWidth + gradientWidth, 0, secondColor, // Termina con el segundo color en la zona del degradado
                    false
            );
            g2d.setPaint(gradient);
            g2d.fillRect(firstColorWidth, 0, gradientWidth, height);

            // Parte sólida del segundo color (el resto del ancho después del degradado)
            GradientPaint secondGradient = new GradientPaint(
                    firstColorWidth + gradientWidth, 0, secondColor, // Comienza con el segundo color
                    width, 0, secondColor, // Segundo color hasta el borde derecho
                    true
            );
            g2d.setPaint(secondGradient);
            g2d.fillRect(firstColorWidth + gradientWidth, 0, width - firstColorWidth - gradientWidth, height);
        }
    }


    class BordeRedondeado2 extends JButton {

        @Override
        protected void paintComponent(Graphics grphcs) {
            Graphics2D g2 = (Graphics2D) grphcs.create(); // Usar create para evitar afectar el original
            g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);

            // Establecer el color de fondo y dibujar el fondo redondeado
            g2.setColor(getBackground());
            g2.fillRoundRect(0, 0, getWidth(), getHeight(), 20, 20);  // Rellenar el fondo redondeado

            // Pintar el borde
            g2.setColor(getForeground());  // Color del borde (normalmente el color del texto)
            g2.drawRoundRect(0, 0, getWidth() - 1, getHeight() - 1, 20, 20); // Dibujar el borde

            super.paintComponent(grphcs);  // Pintar el texto del botón
            g2.dispose();  // Liberar recursos
        }

        @Override
        protected void paintBorder(Graphics g) {
            Graphics2D g2 = (Graphics2D) g.create();
            g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
            g2.setColor(getForeground()); // Color del borde
            g2.drawRoundRect(0, 0, getWidth() - 1, getHeight() - 1, 20, 20); // Borde redondeado
            g2.dispose();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        dpsPrueba = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnMenu = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        dpsEscritorio = new FormaPrincipal();
        jPanel4 = new javax.swing.JPanel();
        btnDoctor = new Menu.BordeRedondeado2();
        btnHome = new Menu.BordeRedondeado2();
        btnPaciente = new Menu.BordeRedondeado2();
        btnBuscar = new Menu.BordeRedondeado2();
        btnEspecialidad = new Menu.BordeRedondeado2();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(125, 165, 232));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Bienvenido");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, -1, -1));

        javax.swing.GroupLayout dpsPruebaLayout = new javax.swing.GroupLayout(dpsPrueba);
        dpsPrueba.setLayout(dpsPruebaLayout);
        dpsPruebaLayout.setHorizontalGroup(
            dpsPruebaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 630, Short.MAX_VALUE)
        );
        dpsPruebaLayout.setVerticalGroup(
            dpsPruebaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
        );

        jPanel1.add(dpsPrueba, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 630, 480));

        jPanel2.setBackground(new java.awt.Color(175, 165, 232));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/menu.png"))); // NOI18N
        btnMenu.setBorderPainted(false);
        btnMenu.setContentAreaFilled(false);
        btnMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });
        jPanel2.add(btnMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("HISTORIAS CLINICAS DE UNA POSTA");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 389, 47));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Logo_Mini.png"))); // NOI18N
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 2, 53, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 50));

        dpsEscritorio.setBackground(new java.awt.Color(255, 255, 255));
        dpsEscritorio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.setOpaque(false);

        btnDoctor.setBackground(new java.awt.Color(153, 153, 255));
        btnDoctor.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        btnDoctor.setForeground(new java.awt.Color(255, 255, 255));
        btnDoctor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Doctor.png"))); // NOI18N
        btnDoctor.setText("Doctores");
        btnDoctor.setBorderPainted(false);
        btnDoctor.setContentAreaFilled(false);
        btnDoctor.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnDoctorMouseMoved(evt);
            }
        });
        btnDoctor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDoctorMouseExited(evt);
            }
        });
        btnDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoctorActionPerformed(evt);
            }
        });

        btnHome.setBackground(new java.awt.Color(153, 153, 255));
        btnHome.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        btnHome.setForeground(new java.awt.Color(255, 255, 255));
        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Home.png"))); // NOI18N
        btnHome.setText("Home");
        btnHome.setBorderPainted(false);
        btnHome.setContentAreaFilled(false);
        btnHome.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnHomeMouseMoved(evt);
            }
        });
        btnHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnHomeMouseExited(evt);
            }
        });

        btnPaciente.setBackground(new java.awt.Color(153, 153, 255));
        btnPaciente.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        btnPaciente.setForeground(new java.awt.Color(255, 255, 255));
        btnPaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Paciente.png"))); // NOI18N
        btnPaciente.setText("Paciente");
        btnPaciente.setBorderPainted(false);
        btnPaciente.setContentAreaFilled(false);
        btnPaciente.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnPacienteMouseMoved(evt);
            }
        });
        btnPaciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPacienteMouseExited(evt);
            }
        });

        btnBuscar.setBackground(new java.awt.Color(153, 153, 255));
        btnBuscar.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Buscar.png"))); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.setBorderPainted(false);
        btnBuscar.setContentAreaFilled(false);
        btnBuscar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnBuscarMouseMoved(evt);
            }
        });
        btnBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBuscarMouseExited(evt);
            }
        });

        btnEspecialidad.setBackground(new java.awt.Color(153, 153, 255));
        btnEspecialidad.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        btnEspecialidad.setForeground(new java.awt.Color(255, 255, 255));
        btnEspecialidad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Especialidad.png"))); // NOI18N
        btnEspecialidad.setText("Especialidad");
        btnEspecialidad.setBorderPainted(false);
        btnEspecialidad.setContentAreaFilled(false);
        btnEspecialidad.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnEspecialidadMouseMoved(evt);
            }
        });
        btnEspecialidad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEspecialidadMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEspecialidad, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                    .addComponent(btnPaciente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDoctor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEspecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
        );

        dpsEscritorio.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 200, 360));

        jPanel1.add(dpsEscritorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 910, 540));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        int posicion = dpsEscritorio.getX();
//        int a=dpsPrueba.getWidth();
//        int b=dpsPrueba.getHeight();
        if (posicion > -1) {
            Animacion.Animacion.mover_izquierda(0, -220, 2, 2, dpsEscritorio);
//            dpsEscritorio.setSize(910+200, 510);
            dpsPrueba.setLocation(dpsPrueba.getX() - 100, dpsPrueba.getY());

        } else {
            Animacion.Animacion.mover_derecha(-220, 0, 2, 2, dpsEscritorio);
//            dpsEscritorio.setSize(910-200, 510);
            dpsPrueba.setLocation(dpsPrueba.getX() + 100, dpsPrueba.getY());
//            Animacion.Animacion.mover_izquierda(0,-70,2,2,dpsPrueba);
        }
    }//GEN-LAST:event_btnMenuActionPerformed

    private void btnHomeMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseMoved
        btnHome.setBorder(BorderFactory.createMatteBorder(0, 10, 0, 0, Color.WHITE));
    }//GEN-LAST:event_btnHomeMouseMoved

    private void btnHomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseExited
        btnHome.setBorder(BorderFactory.createEmptyBorder(0, 0, 0, 0));
    }//GEN-LAST:event_btnHomeMouseExited

    private void btnDoctorMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDoctorMouseMoved
        btnDoctor.setBorder(BorderFactory.createMatteBorder(0, 10, 0, 0, Color.WHITE));
    }//GEN-LAST:event_btnDoctorMouseMoved

    private void btnDoctorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDoctorMouseExited
        btnDoctor.setBorder(BorderFactory.createEmptyBorder(0, 0, 0, 0));
    }//GEN-LAST:event_btnDoctorMouseExited

    private void btnPacienteMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPacienteMouseMoved
        btnPaciente.setBorder(BorderFactory.createMatteBorder(0, 10, 0, 0, Color.WHITE));
    }//GEN-LAST:event_btnPacienteMouseMoved

    private void btnPacienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPacienteMouseExited
        btnPaciente.setBorder(BorderFactory.createEmptyBorder(0, 0, 0, 0));
    }//GEN-LAST:event_btnPacienteMouseExited

    private void btnBuscarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMouseMoved
        btnBuscar.setBorder(BorderFactory.createMatteBorder(0, 10, 0, 0, Color.WHITE));
    }//GEN-LAST:event_btnBuscarMouseMoved

    private void btnBuscarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMouseExited
        btnBuscar.setBorder(BorderFactory.createEmptyBorder(0, 0, 0, 0));
    }//GEN-LAST:event_btnBuscarMouseExited

    private void btnEspecialidadMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEspecialidadMouseMoved
        btnEspecialidad.setBorder(BorderFactory.createMatteBorder(0, 10, 0, 0, Color.WHITE));
    }//GEN-LAST:event_btnEspecialidadMouseMoved

    private void btnEspecialidadMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEspecialidadMouseExited
        btnEspecialidad.setBorder(BorderFactory.createEmptyBorder(0, 0, 0, 0));
    }//GEN-LAST:event_btnEspecialidadMouseExited

    private void btnDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoctorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDoctorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnBuscar;
    public javax.swing.JButton btnDoctor;
    public javax.swing.JButton btnEspecialidad;
    public javax.swing.JButton btnHome;
    public javax.swing.JButton btnMenu;
    public javax.swing.JButton btnPaciente;
    public javax.swing.JPanel dpsEscritorio;
    public javax.swing.JPanel dpsPrueba;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
