/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import javax.swing.JPanel;

/**
 *
 * @author PC
 */
public class Registro extends javax.swing.JFrame {

    /**
     * Creates new form Registro
     */
    public Registro() {
        initComponents();
        txtUsuarioRegis.setBackground(new java.awt.Color(0,0,0,0));  //txt transparente
        txtUsuarioRegis.setOpaque(false); 
        txtContraRegis.setBackground(new java.awt.Color(0,0,0,0));  //txt transparente
        txtContraRegis.setOpaque(false); 
        txtCorreoRegis.setBackground(new java.awt.Color(0,0,0,0));  //txt transparente
        txtCorreoRegis.setOpaque(false); 
        txtTelefonoRegis.setBackground(new java.awt.Color(0,0,0,0));  //txt transparente
        txtTelefonoRegis.setOpaque(false); 
        this.checkOcultar.setVisible(false);
    }

    class DegradoRegistro extends JPanel{  //Para poner un degradado al panel
        protected void paintComponent(Graphics g){
            Graphics2D g2d = (Graphics2D)g ;
            int width = getWidth();
            int height = getHeight();

            Color color1= new Color(175,123,215);
            Color color2= new Color(124,210,243);
            GradientPaint gp = new GradientPaint(0,0,color1,180,height,color2);
            g2d.setPaint(gp);
            g2d.fillRect(0, 0, width, height);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new DegradoRegistro();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtUsuarioRegis = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        txtCorreoRegis = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtTelefonoRegis = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel17 = new javax.swing.JLabel();
        btnRegistrarseRegis = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnVolverIS = new javax.swing.JButton();
        txtContraRegis = new javax.swing.JPasswordField();
        checkVer = new javax.swing.JLabel();
        checkOcultar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("REGISTRO");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Logo_Usuario.png"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 70, -1, 34));

        txtUsuarioRegis.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        txtUsuarioRegis.setForeground(new java.awt.Color(255, 255, 255));
        txtUsuarioRegis.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtUsuarioRegis.setBorder(null);
        jPanel1.add(txtUsuarioRegis, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 228, -1));

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 228, 14));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Logo_Gmail.png"))); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 190, -1, 34));

        txtCorreoRegis.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        txtCorreoRegis.setForeground(new java.awt.Color(255, 255, 255));
        txtCorreoRegis.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCorreoRegis.setBorder(null);
        jPanel1.add(txtCorreoRegis, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 228, -1));

        jSeparator2.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 228, 14));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Logo_Contraseña.png"))); // NOI18N
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, 34));

        jSeparator3.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 228, 14));

        jLabel4.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("CORREO");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, -1, -1));

        jLabel5.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("NOMBRE DE USUARIO");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, -1, -1));

        jLabel6.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("CONTRASEÑA");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, -1, -1));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Logo_Telefono.png"))); // NOI18N
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 250, -1, 34));

        txtTelefonoRegis.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        txtTelefonoRegis.setForeground(new java.awt.Color(255, 255, 255));
        txtTelefonoRegis.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTelefonoRegis.setBorder(null);
        jPanel1.add(txtTelefonoRegis, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 228, -1));

        jSeparator7.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator7.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 228, 14));

        jLabel17.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("TELÈFONO");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, -1, -1));

        btnRegistrarseRegis.setBackground(new java.awt.Color(0, 0, 0));
        btnRegistrarseRegis.setFont(new java.awt.Font("Lucida Sans", 1, 15)); // NOI18N
        btnRegistrarseRegis.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrarseRegis.setText("Registrarse");
        btnRegistrarseRegis.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnRegistrarseRegis.setBorderPainted(false);
        btnRegistrarseRegis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarseRegisActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistrarseRegis, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 130, 47));

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setOpaque(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Si ya tines cuenta");
        jLabel2.setPreferredSize(new java.awt.Dimension(69, 16));
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, -1));

        btnVolverIS.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnVolverIS.setText("Iniciar Sesion");
        btnVolverIS.setBorder(null);
        btnVolverIS.setBorderPainted(false);
        btnVolverIS.setContentAreaFilled(false);
        btnVolverIS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVolverIS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverISActionPerformed(evt);
            }
        });
        jPanel2.add(btnVolverIS, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 80, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 370, 190, 20));

        txtContraRegis.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        txtContraRegis.setForeground(new java.awt.Color(255, 255, 255));
        txtContraRegis.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtContraRegis.setBorder(null);
        jPanel1.add(txtContraRegis, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 228, -1));

        checkVer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Logo_Ver.png"))); // NOI18N
        checkVer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkVerMouseClicked(evt);
            }
        });
        jPanel1.add(checkVer, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, -1, -1));

        checkOcultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Logo_Ocultar.png"))); // NOI18N
        checkOcultar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkOcultarMouseClicked(evt);
            }
        });
        jPanel1.add(checkOcultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarseRegisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarseRegisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistrarseRegisActionPerformed

    private void btnVolverISActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverISActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVolverISActionPerformed

    private void checkVerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkVerMouseClicked
        checkVer.setVisible(false);
        checkOcultar.setVisible(true);
        txtContraRegis.setEchoChar((char)0);
    }//GEN-LAST:event_checkVerMouseClicked

    private void checkOcultarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkOcultarMouseClicked
        checkVer.setVisible(true);
        checkOcultar.setVisible(false);
        txtContraRegis.setEchoChar('*');
    }//GEN-LAST:event_checkOcultarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnRegistrarseRegis;
    public javax.swing.JButton btnVolverIS;
    private javax.swing.JLabel checkOcultar;
    private javax.swing.JLabel checkVer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator7;
    public javax.swing.JPasswordField txtContraRegis;
    public javax.swing.JTextField txtCorreoRegis;
    public javax.swing.JTextField txtTelefonoRegis;
    public javax.swing.JTextField txtUsuarioRegis;
    // End of variables declaration//GEN-END:variables
}
