/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

/**
 *
 * @author PC
 */
public class VistaDoctor extends javax.swing.JPanel {

    /**
     * Creates new form Fondo2
     */
    public VistaDoctor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jPanel2 = new javax.swing.JPanel();
        txtDcod = new javax.swing.JTextField();
        txtDtel = new javax.swing.JTextField();
        txtDnom = new javax.swing.JTextField();
        cbxDesp = new javax.swing.JComboBox<>();
        txtDapel = new javax.swing.JTextField();
        btnDnuevo = new javax.swing.JButton();
        btnDingresar = new javax.swing.JButton();
        btnDborrar = new javax.swing.JButton();
        btnDbuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDregistro = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(630, 480));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jInternalFrame1.setVisible(true);
        jInternalFrame1.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 102, 102));

        txtDcod.setBorder(javax.swing.BorderFactory.createTitledBorder("CODIGO"));
        txtDcod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDcodActionPerformed(evt);
            }
        });

        txtDtel.setBorder(javax.swing.BorderFactory.createTitledBorder("TELEFONO"));

        txtDnom.setBorder(javax.swing.BorderFactory.createTitledBorder("NOMBRES"));

        cbxDesp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CIRUJANO", "PSICOLOGO", "PEDIATRA", "CARDIOLOGO", "DERMATOLOGO" }));
        cbxDesp.setBorder(javax.swing.BorderFactory.createTitledBorder("ESPECIALIDAD"));

        txtDapel.setBorder(javax.swing.BorderFactory.createTitledBorder("APELLIDOS"));

        btnDnuevo.setText("NUEVO");

        btnDingresar.setText("INGRESAR");

        btnDborrar.setText("BORRAR");

        btnDbuscar.setText("BUSCAR");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtDcod)
                    .addComponent(txtDnom)
                    .addComponent(txtDtel)
                    .addComponent(cbxDesp, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDapel)
                    .addComponent(btnDnuevo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDingresar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDborrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDbuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(8, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(txtDcod, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDnom, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDapel, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxDesp, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDtel, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDnuevo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDingresar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDborrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDbuscar)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jInternalFrame1.getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 450));

        tblDregistro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblDregistro);

        jInternalFrame1.getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 490, 450));

        add(jInternalFrame1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 480));
    }// </editor-fold>//GEN-END:initComponents

    private void txtDcodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDcodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDcodActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnDborrar;
    public javax.swing.JButton btnDbuscar;
    public javax.swing.JButton btnDingresar;
    public javax.swing.JButton btnDnuevo;
    public javax.swing.JComboBox<String> cbxDesp;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable tblDregistro;
    public javax.swing.JTextField txtDapel;
    public javax.swing.JTextField txtDcod;
    public javax.swing.JTextField txtDnom;
    public javax.swing.JTextField txtDtel;
    // End of variables declaration//GEN-END:variables
}
